corpus_file_path: "example_corpus_data.txt"
vector_file_path: "vectors.txt" 
model_file_path: "model.keras"
audio_settings:
  sample_rate: 44100
adsr_minimum:
  sustain: 0
  release: 0.01
adsr_maximum:
  attack: 1
  decay: 1
  sustain: 0.8 #1 # Should never be higher than 1
  release: 3
lfo_maximum:
  freq: 20
  depth: 5
adsr_skew_factor: 1 #2.5
lfo_skew_factor: 15
osc_skew_factor: 3 # Go below 1 at your own risk
k: 5 # For KNN weighted average
augmentation_factor: 1 # For neural data augmentation (minimum 1)
training_parameters:
  batch_size: 1
  epochs: 20